import { TBuildingTerritory } from "./BuildingTerritory";

export const buildings: TMockBuilding[] = [
    {
        id: 1,
        name: "Connect",
        keyword: "01J9ZZBD5ZYTDYBAY1ZZQS6YQB",
        address: "Bakı şəhər, Dərnəgül yolu",
        numberOfFloors: 4,
        numberOfRooms: 130,
        emptyRooms: 55,
        numberOfRoomsForRent: 75,
        areaOfRoomsForRent: 100,
        areaEmptyRooms: 555,
        imgUrl: "https://i.pinimg.com/736x/a0/a7/46/a0a746eee27dcbd84359a5557e096da7.jpg",
        totalArea: 400,
        total_debt: 120.0,
        official_payment: 12.24,
        unofficial_payment: 34,
        statistics: [
            {
                id: "01J678FWHY7A2C7MJDMRCF91KZ",
                keyword: "01J678FWHY7A2C7MJDMRCF91KZ",
                name: "Mərtəbə bir",
                countOfRooms: 160,
                emptyRooms: 55,
                countOfRoomsForRent: 75,
                areaOfRoomsForRent: 100,
                areaEmptyRooms: 555,
                totalArea: 565,
                total_debt: 120.0,
                official_payment: 12.24,
                unofficial_payment: 34,
            },
            {
                id: "01J67AREJ7JWTRZ26G23QZJ0CC",
                keyword: "01J67AREJ7JWTRZ26G23QZJ0CC",
                name: "Mərtəbə iki",
                countOfRooms: 10,
                emptyRooms: 5,
                countOfRoomsForRent: 5,
                areaOfRoomsForRent: 100,
                areaEmptyRooms: 12,
                totalArea: 112,
                total_debt: 56.0,
                official_payment: 12.24,
                unofficial_payment: 34,
            },
            {
                id: "01J678FWHY7A2C7MJDMRCF91KZ",
                keyword: "01J678FWHY7A2C7MJDMRCF91KZ",
                name: "Mərtəbə üç",
                countOfRooms: 60,
                emptyRooms: 55,
                countOfRoomsForRent: 5,
                areaOfRoomsForRent: 100,
                areaEmptyRooms: 555,
                totalArea: 655,
                total_debt: 0.0,
                official_payment: 12.24,
                unofficial_payment: 34,
            },
            {
                id: "01J67AREJ7JWTRZ26G23QZJ0CC",
                keyword: "01J67AREJ7JWTRZ26G23QZJ0CC",
                name: "Zirzəmi",
                countOfRooms: 10,
                emptyRooms: 5,
                countOfRoomsForRent: 5,
                areaOfRoomsForRent: 100,
                areaEmptyRooms: 12,
                totalArea: 12,
                total_debt: 520.0,
                official_payment: 142.24,
                unofficial_payment: 343,
            },
        ],
    },
    {
        id: 2,
        name: "Elektroterm",
        keyword: "electrotherm",
        address: "Bakı şəhər, Dərnəgül yolu",
        numberOfFloors: 42,
        numberOfRooms: 43,
        emptyRooms: 54,
        numberOfRoomsForRent: 100,
        areaOfRoomsForRent: 150,
        areaEmptyRooms: 55,
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVgmoCOGRcAgjHbNluxWmJjBV6R54nT8KGPXpHkRK3pHfbUzhCEA_qS044aeXNiyD2wOs&usqp=CAU",
        totalArea: 1000,
        total_debt: 230.0,
        official_payment: 12.24,
        unofficial_payment: 34,
        statistics: [
            {
                id: "01J678FWHY7A2C7MJDMRCF91KZ",
                keyword: "01J678FWHY7A2C7MJDMRCF91KZ",
                name: "Mərtəbə bir",
                countOfRooms: 60,
                emptyRooms: 55,
                countOfRoomsForRent: 5,
                areaOfRoomsForRent: 100,
                areaEmptyRooms: 555,
                totalArea: 655,
                total_debt: 0.0,
                official_payment: 12.24,
                unofficial_payment: 34,
            },
            {
                id: "01J678FWHY7A2C7MJDMRCF91KZ",
                keyword: "01J678FWHY7A2C7MJDMRCF91KZ",
                name: "Mərtəbə iki",
                countOfRooms: 60,
                emptyRooms: 55,
                countOfRoomsForRent: 5,
                areaOfRoomsForRent: 100,
                areaEmptyRooms: 555,
                totalArea: 655,
                total_debt: 0.0,
                official_payment: 12.24,
                unofficial_payment: 34,
            },
            {
                id: "01J678FWHY7A2C7MJDMRCF91KZ",
                keyword: "01J678FWHY7A2C7MJDMRCF91KZ",
                name: "Mərtəbə üç",
                countOfRooms: 60,
                emptyRooms: 55,
                countOfRoomsForRent: 5,
                areaOfRoomsForRent: 100,
                areaEmptyRooms: 555,
                totalArea: 655,
                total_debt: 0.0,
                official_payment: 12.24,
                unofficial_payment: 34,
            },
        ],
    },
    {
        id: 3,
        name: "As Texnika",
        keyword: "asTechnology",
        address: "Bakı şəhər, Dərnəgül yolu",
        numberOfFloors: 23,
        numberOfRooms: 34,
        emptyRooms: 55,
        numberOfRoomsForRent: 10,
        areaOfRoomsForRent: 100,
        areaEmptyRooms: 55,
        imgUrl: "https://www.shutterstock.com/image-illustration/3d-render-conceptual-urban-building-600nw-1855601581.jpg",
        totalArea: 1000,
        total_debt: 230.0,
        official_payment: 12.24,
        unofficial_payment: 34,
        statistics: [
            {
                id: "01J678FWHY7A2C7MJDMRCF91KZ",
                keyword: "01J678FWHY7A2C7MJDMRCF91KZ",
                name: "Mərtəbə bir",
                countOfRooms: 60,
                emptyRooms: 55,
                countOfRoomsForRent: 5,
                areaOfRoomsForRent: 100,
                areaEmptyRooms: 555,
                totalArea: 655,
                total_debt: 0.0,
                official_payment: 12.24,
                unofficial_payment: 34,
            },
            {
                id: "01J678FWHY7A2C7MJDMRCF91KZ",
                keyword: "01J678FWHY7A2C7MJDMRCF91KZ",
                name: "Mərtəbə iki",
                countOfRooms: 60,
                emptyRooms: 55,
                countOfRoomsForRent: 5,
                areaOfRoomsForRent: 100,
                areaEmptyRooms: 555,
                totalArea: 655,
                total_debt: 0.0,
                official_payment: 12.24,
                unofficial_payment: 34,
            },
            {
                id: "01J678FWHY7A2C7MJDMRCF91KZ",
                keyword: "01J678FWHY7A2C7MJDMRCF91KZ",
                name: "Mərtəbə üç",
                countOfRooms: 60,
                emptyRooms: 55,
                countOfRoomsForRent: 5,
                areaOfRoomsForRent: 100,
                areaEmptyRooms: 555,
                totalArea: 655,
                total_debt: 0.0,
                official_payment: 12.24,
                unofficial_payment: 34,
            },
            {
                id: "01J678FWHY7A2C7MJDMRCF91KZ",
                keyword: "01J678FWHY7A2C7MJDMRCF91KZ",
                name: "Mərtəbə dörd",
                countOfRooms: 60,
                emptyRooms: 55,
                countOfRoomsForRent: 5,
                areaOfRoomsForRent: 100,
                areaEmptyRooms: 555,
                totalArea: 655,
                total_debt: 0.0,
                official_payment: 12.24,
                unofficial_payment: 34,
            },
            {
                id: "01J678FWHY7A2C7MJDMRCF91KZ",
                keyword: "01J678FWHY7A2C7MJDMRCF91KZ",
                name: "Terrace",
                countOfRooms: 60,
                emptyRooms: 55,
                countOfRoomsForRent: 5,
                areaOfRoomsForRent: 100,
                areaEmptyRooms: 555,
                totalArea: 655,
                total_debt: 0.0,
                official_payment: 12.24,
                unofficial_payment: 34,
            },
        ],
    },
    {
        id: 4,
        name: "BSM",
        keyword: "bsm",
        address: "Bakı şəhər",
        numberOfFloors: 4,
        numberOfRooms: 4,
        emptyRooms: 5,
        numberOfRoomsForRent: 10,
        areaOfRoomsForRent: 100,
        areaEmptyRooms: 55,
        totalArea: 1000,
        imgUrl: "https://surplus.lk/wp-content/uploads/2021/02/1_1725.jpg",
        statistics: [],
        total_debt: 0,
        official_payment: 0,
        unofficial_payment: 0,
    },
    {
        id: 5,
        name: "Istehsalat",
        keyword: "industrial",
        address: "Bakı şəhər, Dərnəgül yolu",
        numberOfFloors: 4,
        numberOfRooms: 15,
        emptyRooms: 5,
        numberOfRoomsForRent: 10,
        areaOfRoomsForRent: 100,
        areaEmptyRooms: 55,
        imgUrl: "https://i.pinimg.com/736x/a0/a7/46/a0a746eee27dcbd84359a5557e096da7.jpg",
        totalArea: 1000,
        statistics: [],
        total_debt: 0,
        official_payment: 0,
        unofficial_payment: 0,
    },
    {
        id: 6,
        name: "Planirovka",
        keyword: "planning",
        address: "Bakı şəhər, Dərnəgül yolu",
        numberOfFloors: 4,
        numberOfRooms: 15,
        emptyRooms: 5,
        numberOfRoomsForRent: 10,
        areaOfRoomsForRent: 100,
        areaEmptyRooms: 55,
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVgmoCOGRcAgjHbNluxWmJjBV6R54nT8KGPXpHkRK3pHfbUzhCEA_qS044aeXNiyD2wOs&usqp=CAU",
        totalArea: 1000,
        statistics: [
            {
                id: "01J678FWHY7A2C7MJDMRCF91KZ",
                keyword: "01J678FWHY7A2C7MJDMRCF91KZ",
                name: "Mərtəbə bir",
                countOfRooms: 160,
                emptyRooms: 55,
                countOfRoomsForRent: 75,
                areaOfRoomsForRent: 100,
                areaEmptyRooms: 555,
                totalArea: 565,
                total_debt: 120.0,
                official_payment: 12.24,
                unofficial_payment: 34,
            },
            {
                id: "01J67AREJ7JWTRZ26G23QZJ0CC",
                keyword: "01J67AREJ7JWTRZ26G23QZJ0CC",
                name: "Mərtəbə iki",
                countOfRooms: 10,
                emptyRooms: 5,
                countOfRoomsForRent: 5,
                areaOfRoomsForRent: 100,
                areaEmptyRooms: 12,
                totalArea: 112,
                total_debt: 56.0,
                official_payment: 12.24,
                unofficial_payment: 34,
            },
        ],
        total_debt: 0,
        official_payment: 0,
        unofficial_payment: 0,
    },
];

export type TMockBuilding = {
    id: number;
    name: string;
    keyword: string;
    address: string;
    numberOfFloors: number;
    numberOfRooms: number;
    emptyRooms: number;
    totalArea: number;
    total_debt: number;
    numberOfRoomsForRent: number;
    areaOfRoomsForRent: number;
    official_payment: number;
    unofficial_payment: number;
    areaEmptyRooms: number;
    imgUrl: string;
    statistics: TFloorStatistics[];
};

export type TFloorStatistics = {
    id: string;
    keyword: string;
    name: string;
    countOfRooms: number;
    emptyRooms: number;
    countOfRoomsForRent: number;
    areaOfRoomsForRent: number;
    areaEmptyRooms: number;
    totalArea: number;
    total_debt: number;
    official_payment: number;
    unofficial_payment: number;
};

export const territoryBuilding: TBuildingTerritory = {
    id: "01JASKZ8X4GS8NMN5601R4Q5MK",
    company_id: "01JASKZ8W5592RW5S0YAFDPBVT",
    name: "Ərazi",
    address: "Bak\u0131 \u015f\u0259h\u0259ri",
    is_erazi: false,
};
